export const mockBookData = [
  {
    isbn: 'string',
    author: '유발 하라리',
    publisher: '김영사',
    content: '설명',
    datetime: '2015.11.24',
    label: '자기개발',
    thumbnailURL: 'string',
    type: 'paper',
    bookLink: 'string',
    mainCategoryKey: 0,
    subCategoryKey: 0,
    status: 'available',
    bookId: '1',
    title: 'Do it! 자료 구조와 함께 배우는 알고리즘 입문',
  },
  {
    isbn: 'string',
    author: '유발 하라리',
    publisher: '김영사',
    content: '설명',
    datetime: '2015.11.24',
    label: '자기개발',
    thumbnailURL: 'string',
    type: 'paper',
    bookLink: 'string',
    mainCategoryKey: 0,
    subCategoryKey: 0,
    status: 'available',
    bookId: '2',
    title: 'Do it! 자료 구조와 함께 배우는 알고리즘 입문',
  },
  {
    isbn: 'string',
    author: '유발 하라리',
    publisher: '김영사',
    content: '설명',
    datetime: '2015.11.24',
    label: '자기개발',
    thumbnailURL: 'string',
    type: 'paper',
    bookLink: 'string',
    mainCategoryKey: 0,
    subCategoryKey: 0,
    status: 'available',
    bookId: '3',
    title: 'Do it! 자료 구조와 함께 배우는 알고리즘 입문',
  },
  {
    isbn: 'string',
    author: '유발 하라리',
    publisher: '김영사',
    content: '설명',
    datetime: '2015.11.24',
    label: '자기개발',
    thumbnailURL: 'string',
    type: 'paper',
    bookLink: 'string',
    mainCategoryKey: 0,
    subCategoryKey: 0,
    status: 'available',
    bookId: '3',
    title: 'Do it! 자료 구조와 함께 배우는 알고리즘 입문',
  },
  {
    isbn: 'string',
    author: '유발 하라리',
    publisher: '김영사',
    content: '설명',
    datetime: '2015.11.24',
    label: '자기개발',
    thumbnailURL: 'string',
    type: 'paper',
    bookLink: 'string',
    mainCategoryKey: 0,
    subCategoryKey: 0,
    status: 'available',
    bookId: '3',
    title: 'Do it! 자료 구조와 함께 배우는 알고리즘 입문',
  },
  {
    isbn: 'string',
    author: '유발 하라리',
    publisher: '김영사',
    content: '설명',
    datetime: '2015.11.24',
    label: '자기개발',
    thumbnailURL: 'string',
    type: 'paper',
    bookLink: 'string',
    mainCategoryKey: 0,
    subCategoryKey: 0,
    status: 'available',
    bookId: '3',
    title: 'Do it! 자료 구조와 함께 배우는 알고리즘 입문',
  },
];
