export const ROUTE_PATH = {
  SERVICE: '/service',
  SERVICE_BOOK_LIST: '/service/book-list',
  SERVICE_ADD_BOOKS: '/service/add-books',
  SERVICE_MY_RENT: '/service/my-rent',
  SERVICE_MEMBER_MANAGEMENT: '/service/member-management',
  SERVICE_INQUIRY: '/service/inquiry',
  SERVICE_SETTING: '/service/setting',
  SIGN_IN: '/register/sign-in',
  SIGN_UP: '/register/sign-up',
  FORGET_PASSWORD: '/register/forget-password',
  REGISTER_ENTRY: '/register-entry',
  MAKE_GROUP: '/make-group',
  REGISTER: '/register',
  HOME: '/home',
  INFO: '/info',
  SERVICE_MODAL_ID: '/service/modal/:id',
  SERVICE_BOOK_LIST_MODAL_ID: '/service/book-list/:id',
};
