export const mockBookData = [
  {
    isbn: 'string',
    authors: ['유발 하라리'],
    publisher: '김영사',
    content: '설명',
    datetime: '2015.11.24',
    label: '자기개발',
    thumbnailURL: 'http://search3.kakaocdn.net/argon/130x130_85_c/7r6ygzbvBDc',
    type: 'paper',
    bookLink: 'string',
    mainCategoryKey: 0,
    subCategoryKey: 0,
    status: 'available',
    bookId: '1',
    title: 'Do it! 자료 구조와 함께 배우는 알고리즘 입문',
  },

];

export const returnBookData = [
  {
    returnedAt: "2020-12-07T10:02:18.354Z",
    rentedAt: "2020-12-07T10:02:18.354Z",
    isbn: 'string',
    authors: ['유발 하라리'],
    publisher: '김영사',
    content: '설명',
    datetime: '2015.11.24',
    label: '자기개발',
    thumbnailURL: 'http://search3.kakaocdn.net/argon/130x130_85_c/7r6ygzbvBDc',
    type: 'paper',
    bookLink: 'string',
    mainCategoryKey: 0,
    subCategoryKey: 0,
    status: 'available',
    bookId: 1,
    rentalId: 1,
    title: 'Do it! 자료 구조와 함께 배우는 알고리즘 입문 보다 더 긴 제목',
  },
  {
    returnedAt: "2020-12-07T10:02:18.354Z",
    rentedAt: "2020-12-07T10:02:18.354Z",
    isbn: 'string',
    authors: ['유발 하라리'],
    publisher: '김영사',
    content: '설명',
    datetime: '2015.11.24',
    label: '자기개발',
    thumbnailURL: 'http://search3.kakaocdn.net/argon/130x130_85_c/7r6ygzbvBDc',
    type: 'paper',
    bookLink: 'string',
    mainCategoryKey: 0,
    subCategoryKey: 0,
    status: 'available',
    bookId: 2,
    rentalId: 2,
    title: '알고리즘 입문',
  },
]
